---
banknotes:
  500: 0
  200: 0
  100: 2
  50: 1
  20: 2
  10: 4
  5: 1
  2: 0
  1: 2
accounts:
  3321:
    name: Volodymyr
    password: "$2a$10$8Fowm3oDVSdSUl4HwxVrouJudKONnrmLZbmsgZKCx7Hcfhr2/VY4O"
    balance: '422'
  5922:
    name: Iryna
    password: "$2a$10$Fv10iwB7QCUJwTGv28yzGuSYSNe9HN17RjtEqJf4/oGdeAiHAGsDC"
    balance: '4311'
